### ISSUE TITLE
ActionBarActivity was deprecated

### ISSUE THREAD

**Issue by ooscarr** [ksoichiro/Android-ObservableScrollView#109]
Android Support Library, revision 22.1.0 (April 2015) deprecated ActionBarActivity in favor of AppCompatActivity, for the sample app code update (just extend AppCompatActivity in the BaseActivity class).

And they also added a new NestedScrollView class to support nested scrolling parent and child
http://developer.android.com/reference/android/support/v4/widget/NestedScrollView.html
which can be interesting and fun.

Excellent library, thanks.

**Comment by ksoichiro** [comment]
@ooscarr Thank you for the information.
I'll replace ActionBarActivity to AppCompatActivity in the sample.
Also I'm going to check the NestedScrollView later.
