### ISSUE TITLE
How to Begin

### ISSUE THREAD

**Issue by speakright** [ksoichiro/Android-ObservableScrollView#110]
Hi sir,

This is not an issue at all. I mean. I have at least 6 months programming on android. I am not a noobneather an expert, I am in the middle. For this reason, I ask to you an idea on how to begin to develop something like "viewpager + tab + scrollview" as you show on your page. I don't know how or where to start to implement your librery. It is complete and super useful, but I need a little push.

Thank you very much in advance. And may the 4th with you, soon.

**Comment by moslem-pc** [comment]
why no answers or comments? :|
