### ISSUE TITLE
ViewPagerTabScrollViewActivity behaviour on single tap

### ISSUE THREAD

**Issue by ffalcinelli** [ksoichiro/Android-ObservableScrollView#118]
First of all, thanks a lot for making our lives easier :-)

Anyway, I noticed a quite strange behaviour: when switching on a tab different from the first, if I tap one time the ScrollView area, the tab switches back. Sometimes it's stacked between one and another, having the indicator on the previous and the highlighted tab name on the next.

I've just cloned 49db40502b75930b060c4b4087a50398dca27e5b and this problem seems to happen on Android 4.3 (Galaxy Nexus) and 5.0.2 (Moto G).

It's not easy to reproduce with an emulator, but performing simple single taps on a device shows it up.

Any idea or hint to workaround or solve this is really appreciated.

**Comment by ksoichiro** [comment]
Hi, thank you for the feedback.
Is that related to #117?
I found a workaround for that problem, and it might also be useful for your issue.

**Comment by ffalcinelli** [comment]
Yes, It could be related, I'll check it up and let you know as soon as possible

**Comment by ffalcinelli** [comment]
Yes, It is related, and indeed it solved the issue. Thanks a lot!
