### ISSUE TITLE
Build failed for minSdkVersion 8 app.

### ISSUE THREAD

**Issue by DanKCl** [ksoichiro/Android-ObservableScrollView#125]
Hello.... i came across your library and would like try to introduce it into my app by following your guideline here: http://ksoichiro.github.io/Android-ObservableScrollView/docs/quick-start/dependencies but I encounter an error stating: 
" Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 8 cannot be smaller than version 9 declared in library " while trying to configure into my build.gradle.

I wonder does your library support api 8 too? I'm try to make an app that can support at least api 8 and I noticed that from https://github.com/ksoichiro/Android-ObservableScrollView/issues/58 mentioned he is able to run in (APIs: 8, 11, 15, 19, 21). Would like to hear from you. I'm quite new on this. Thanks..

**Comment by ksoichiro** [comment]
Unfortunately, it doesn't support API level 8.

But if you want to build it for API level 8, you can do it by adding `tools:overrideLibrary` attribute to your AndroidManifest.xml.
Like this:

```xml
<uses-sdk
    android:minSdkVersion="8"
    android:targetSdkVersion="22"
    tools:overrideLibrary="com.github.ksoichiro.android.observablescrollview" />
```

**Comment by ksoichiro** [comment]
Closing the issue. Please reopen it if your problem is not solved yet.
