### ISSUE TITLE
Update copyright year in Readme

### ISSUE THREAD

**Issue by anticafe** [ksoichiro/Android-ObservableScrollView#128]
In your [Readme > License](https://github.com/ksoichiro/Android-ObservableScrollView#license)
>Copyright 2014 Soichiro Kashima

It should be 2015.

**Comment by ksoichiro** [comment]
Thanks for the feedback.
As far as I know, 2014 is correct because it is the year when this project was published (not this year).

**Comment by ksoichiro** [comment]
Closing the issue.
If you think it should be fixed, please reopen the issue and tell me your opinion.
