### ISSUE TITLE
Deprecate getChildPosition - (RecyclerView)

### ISSUE THREAD

**Issue by jrura18** [ksoichiro/Android-ObservableScrollView#131]
https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html#getChildPosition(android.view.View)

**Comment by ksoichiro** [comment]
Thank you for this information.
I'll replace it to some new APIs in the near future.

**Comment by ksoichiro** [comment]
Fixed this in the commit e308b60.
(`getChildAdapterPosition()` method doesn't exist on `recyclerview-v7:21`,
and this handles it in case someone still needs to use `recyclerview-v7:21`.)

**Comment by elirehema** [comment]
https://stackoverflow.com/questions/41977376/deprecated-getchildposition-in-recyclerview-in-android
