### ISSUE TITLE
Support Design Library

### ISSUE THREAD

**Issue by panagorn** [ksoichiro/Android-ObservableScrollView#142]
Hello and thank you for the great library. I wanted to ask if there is any way so you can implement some of the functionality with the new android support design library. Thank you

**Comment by vsahu1986** [comment]
+1 
yeah support design library has many feature to maintain scrolling in multiple tabs , but this library has written keeping in mind that every scroll component behave it own way . 

Many thank to Ksoichiro ..

**Comment by AndroidDeveloperLB** [comment]
The design library already has something very similar to what's shown here. Check out this repo:
https://github.com/chrisbanes/cheesesquare
