### ISSUE TITLE
How to implement the SlidingUpScrollView?

### ISSUE THREAD

**Issue by asdfg60842** [ksoichiro/Android-ObservableScrollView#146]
I try to implemnt this function with AIDE in my project of activity_main , but BaseActivity and SlidingUpBaseActivity has many error inside of the Android Observable master......
What is the strange? I think its hard and you are so awasome

**Comment by ksoichiro** [comment]
Sorry but this project doesn't support AIDE currently, so I can't imagine what they would be like.
What kind of errors do you see?

**Comment by asdfg60842** [comment]
Almost clear all error but Adding android.support.v7 appcompat  I have an
error to AppCompatActivity in BaseActivity.java .... So I modify
AppCompatActivity instead ActionBarActivity.
It happen problem?

Thank you answer for my question
2015. 6. 10. 오후 11:43에 "Soichiro Kashima" <notifications@github.com>님이 작성:

**Comment by ksoichiro** [comment]
Are you using appcompat-v7:22.1+?
I replaced ActionBarActivity to AppCompatActivity in commit cc73c69,
because ActionBarActivity is deprecated since v22.1.
But maybe you can still use ActionBarActivity.

**Comment by ksoichiro** [comment]
If you use only SlidingUp examples in your app, perhaps you don't have to use ActionBarActivity or AppCompatActivity because they don't depend on ActionBars.
(BaseActivity extends AppCompatActivity because some of the subclasses use ActionBar.)
So just extending normal Activity and removing ActionBar-related codes from the example codes would be enough for your case.

**Comment by asdfg60842** [comment]
Oh I get it Thank you ksoichiro .
I make sure to implement SlidingUp .
Have a nice day
2015. 6. 11. 오전 12:37에 "Soichiro Kashima" <notifications@github.com>님이 작성:

**Comment by ksoichiro** [comment]
Closing issue.
Please reopen it if you think it's not solved yet.
