### ISSUE TITLE
Lock sliding up scrollview on anchor point.

### ISSUE THREAD

**Issue by acappelli** [ksoichiro/Android-ObservableScrollView#151]
Hi! I want to lock the sliding up on anchor point or bottom point, can you help me on this?
Thanks in advance

**Comment by ksoichiro** [comment]
Hi,

Could you explain what "lock" means?
(Disable scroll?)

**Comment by acappelli** [comment]
Yes disable scroll to top point, I want to scroll only in middle and bottom state.

**Comment by ksoichiro** [comment]
Is this what you want?

![aosv-issue151](https://cloud.githubusercontent.com/assets/801987/8183867/cf70050e-1475-11e5-95fe-d3d9fc26e57d.gif)

You can do this by changing `final int minInterceptionLayoutY = -mIntersectionHeight;`
to`final int minInterceptionLayoutY = (int) getAnchorYImage();` in `SlidingUpBaseActivity`.

This code is around here:

```java
    private TouchInterceptionFrameLayout.TouchInterceptionListener mInterceptionListener = new TouchInterceptionFrameLayout.TouchInterceptionListener() {
        @Override
        public boolean shouldInterceptTouchEvent(MotionEvent ev, boolean moving, float diffX, float diffY) {
            final int minInterceptionLayoutY = -mIntersectionHeight;
```

**Comment by acappelli** [comment]
Yes! You are the best! Thanks

**Comment by ksoichiro** [comment]
It seems to be resolved. Close.
