### ISSUE TITLE
Toolbar sometimes remains in inconsistent state in the demo

### ISSUE THREAD

**Issue by djj0809** [ksoichiro/Android-ObservableScrollView#17]
Hi, firstly thanks for the great library:)

When I try implementing some samples, I found some strange things, and I also reproduced with the official demo, you can see it from the screenshot:
![s41213-214434](https://cloud.githubusercontent.com/assets/1077604/5431324/b76cefca-8461-11e4-97fc-9ad281776796.jpg)
![s41213-214643](https://cloud.githubusercontent.com/assets/1077604/5431325/bbfefb0a-8461-11e4-8b52-a7c5345ca084.jpg)

You can see that the toolbar only show part of it or doesn't show at all when listview or recyclerview has reached its top. These things didn't happen every time, but when you try scrolling it near the top again and again, it will happen sometime. 

I did some simple investigation, maybe problems are from codes below:
```java
    private void adjustToolbar(ScrollState scrollState, View view) {
        int toolbarHeight = mToolbarView.getHeight();
        final Scrollable scrollView = (Scrollable) view.findViewById(R.id.scroll);
        if (scrollView == null) {
            return;
        }
        if (scrollState == ScrollState.UP) {
            if (toolbarHeight < scrollView.getCurrentScrollY()) {
                hideToolbar();
            } else if (scrollView.getCurrentScrollY() < toolbarHeight) {
                showToolbar();
            }
        } else if (scrollState == ScrollState.DOWN) {
            // scrollView.getCurrentScrollY() sometimes returns smaller than toolbarHeight 
            // when your finger left the screen but toolbar is not totally shown, 
            // maybe we should remove this condition statement and always show toolbar?
            if (toolbarHeight < scrollView.getCurrentScrollY()) {
                showToolbar();
            }
        }
    }
```

**Comment by ksoichiro** [comment]
This fix also works but `ViewPagerTab2Activity` that I've recently added seems better than `ViewPagerTabActivity`.
Please check that if you're interested in.
I'll close this issue, so please reopen it or open a new issue if you find any problems.
