### ISSUE TITLE
Problem with Swipe Refresh Layout & ObservableRecyclerView

### ISSUE THREAD

**Issue by Zaitungtung** [ksoichiro/Android-ObservableScrollView#173]
I have the Observable RecyclerView inside a Swipe Refresh Layout, and I implement the show/hide animation as here "ToolbarControlRecyclerViewActivity.java". The problems occurred inside the animation:

private void moveToolbar(float toTranslationY) {
        if (ViewHelper.getTranslationY(mToolbar) == toTranslationY) {
            return;
        }
        ValueAnimator animator = ValueAnimator.ofFloat(ViewHelper.getTranslationY(mToolbar), toTranslationY).setDuration(200);
        animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            @Override
            public void onAnimationUpdate(ValueAnimator animation) {
                float translationY = (float) animation.getAnimatedValue();
                ViewHelper.setTranslationY(mToolbar, translationY);
                ViewHelper.setTranslationY(mScrollable, translationY);
                ViewGroup.LayoutParams lp = (ViewGroup.LayoutParams) (mScrollable).getLayoutParams();
                lp.height = (int) -translationY + getScreenHeight() - lp.height;
                (mScrollable).requestLayout();
            }
        });
        animator.start(); ""

As you can see, I should to cast the Scrollable Layout Parameters as ViewGroup (Swipe Refresh type) instead of Linear Layout, and the problem is that ViewGroup haven't got the topMargin property that need in the next line, to calculate the height.

**Comment by nabir** [comment]
Did you manage to fix this?
