### ISSUE TITLE
FlexibleSpaceWithImageRecyclerViewActivity with sticky Toolbar

### ISSUE THREAD

**Issue by borgwald** [ksoichiro/Android-ObservableScrollView#175]
Hello,

on your MainPage in your first animated Example with FlexibleSpaceWithImage, the Toolbar is sticky. When implementing your code for FlexibleSpaceWithImageRecyclerViewActivity the Toolbar scrolls after reaching the flexible_space_image_height. How can i achieve a sticky Toolbar that is always visible?

**Comment by BRdev** [comment]
I'm dealing with the same issue. How did you fix this?
