### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Tomblarom** [ksoichiro/Android-ObservableScrollView#193]
![tqtas1d](https://cloud.githubusercontent.com/assets/12703270/9356149/f471c442-467e-11e5-9da9-a4a18e9a4e2e.png)

I am not sure what exactly causing this error and what you need to fix it. Its occouring `on mouse over` and `on click on ArrayIndexOutOfBoundsException`

**Comment by ksoichiro** [comment]
Sorry for my late reply.
Have you already resolved this issue?
I'm not sure but I think this is an IDE issue.

I'm closing this issue for now, but if you're still suffering from it,
please reopen and give me some more details (e.g. stacktrace of ArrayIndexOutOfBoundsException).
