### ISSUE TITLE
Update the support libs!

### ISSUE THREAD

**Issue by kabouzeid** [ksoichiro/Android-ObservableScrollView#197]

**Comment by ksoichiro** [comment]
Sorry for my late reply.

support-v4 is a transitive dependency of recyclerview-v7.
If you want to update the version of support-v4 lib,
you can do it by configuring your build.gradle
to exclude recyclerview-v7 and add it again with your desired version:

```gradle
dependencies {
    compile('com.github.ksoichiro:android-observablescrollview:1.6.0') {
        exclude module: 'recyclerview-v7'
    }
    compile 'com.android.support:recyclerview-v7:xxx'
    compile 'com.android.support:support-v4:xxx'
}
```

I'll close this issue but if you are talking about compatibility problem
(e.g. in newer version of support-v4, some APIs are removed and this lib uses them, 
which causes app crashing), please reopen the issue and let me know details.
