### ISSUE TITLE
Should notify some callbacks, like ViewPager.

### ISSUE THREAD

**Issue by numa08** [ksoichiro/Android-ObservableScrollView#205]
Now,　ObservableScrollView/ListView/WebView/GridView/RecyclerView has 1-1 relationship between callback.

And, ViewPager was modified to add/remove OnPageChangeListener. Then, that change it was enable to more useful.

I think, should this library been change, like ViewPager ?

**Comment by ksoichiro** [comment]
@numa08 Thank you for the PR! Looks good to me.

**Comment by ksoichiro** [comment]
Thanks, I've merged it. I'll release it soon.
