### ISSUE TITLE
Using translucent status bar with Flexible Space with image

### ISSUE THREAD

**Issue by 535A2** [ksoichiro/Android-ObservableScrollView#23]
Hi,
I'm using the FlexibleSpaceWithScrollView and I'm attempting to use the translucent status bar from android 5.0 with it. This however puts the toolbar and title text behind the status bar. Fixing the toolbar was easy enough, but I can't figure out how to properly get the title text to be lower as well.

Any tips?
Thanks for this great library.

**Comment by clopeziiia** [comment]
What value did you use¿

**Comment by 535A2** [comment]
You mean the value for `android:minHeight`?
I believe I used `mTitleView.setMinHeight(mActionBarSize - getStatusBarHeight());`
To calculate the status bar size I used the answer from here: http://stackoverflow.com/questions/3407256/height-of-status-bar-in-android

**Comment by clopeziiia** [comment]
Thanks, I'll try. I was trying with mActionBarSize + getStatusBarHeight() wrongly...
