### ISSUE TITLE
ViewPagerTabListView/RecyclerView without using dummy padding as first item?

### ISSUE THREAD

**Issue by dexcell** [ksoichiro/Android-ObservableScrollView#25]
Hi @ksoichiro 

Sorry it's me again.
I have a problem with view pager with sliding tab layout example.

The problem with current example is
- sometimes when you try scroll or slide a lot, you can see the blank padding / first item.
- the vertical scroll indicator become strange because there is one item hidden below the tab.
- when there is swiperefreshlayout, the refresh indicator became partially visible (hidden below the tab)

I tried to use another approach without using dummy padding item for hours but luckily i didn't get the good result :(

I found an app example, it's not material spec but it has the similar flow of design, and i think they did correctly. Here is the link.
https://play.google.com/store/apps/details?id=jp.gocro.smartnews.android

Notice in the app when we scroll the listview/recycler down, the scrollbar doesn't showup but the tabs and the content moves up then after the tab reach the top, then we can scroll the listview/recyclerview.

Any ideas how to accomplish this?
Help is very appreciated.

Thank you

**Comment by ksoichiro** [comment]
It's now released as the version 1.4.0 (not a snapshot), and it works currently.
Thank you for reporting this issue.
Maybe this is a better solution to achieve ViewPager pattern than one that uses dummy paddings.

I'll close this issue, so please reopen this or open a new issue if you have any problems or questions.
