### ISSUE TITLE
SlidingUp improvements

### ISSUE THREAD

**Issue by acappelli** [ksoichiro/Android-ObservableScrollView#32]
Hi!
I have an idea to improve the slidingUp.
When you slide the panel must appears on the top an image with parallax effect, in this way on the finish of slide we have a FlexibleSpaceWithImage, and if you continue the scroll the image disappears like your example! What do you think?

**Comment by ksoichiro** [comment]
These updates are released to the Play store, so I'll close this issue.
Please open a new issue if you have any questions or problems.

**Comment by mdakram** [comment]
@ksoichiro  Thanks for this awesome open source can we implement "Sliding up effect with ScrollView" using viewpager, each item in ViewPager has a scrollView.
