### ISSUE TITLE
Problem running project on eclipse

### ISSUE THREAD

**Issue by panagorn** [ksoichiro/Android-ObservableScrollView#34]
When i import  this project on eclipse i get multiple errors in manifest.xml in here <category android:name="${applicationId}" /> and other errors in .java files here  float height = (float) animation.getAnimatedValue(); cannot cast from object to float. any help will be appreciated

**Comment by Assafgot** [comment]
compile the project in java 1.7 will resolve your compilation error on  cannot cast from object to float..

**Comment by androidvsourz** [comment]
Great !!! It works now once i have changed my java compiler from 1.6 to 1.7

Just follow below steps for sample project as well as for library ::

You can set overall workspace properties to use one version of Java and set individual project properties to use another.

To set overall workspace properties, click on Window > Preferences, then navigate to Java > Compiler.
To set project properties, right-click on the project and select Properties. Navigate to Java Compiler and check "Enable project specific settings"
You can choose from among the installed JREs for either setting. To tell Eclipse about a newly installed JRE, you can open the workspace preferences and navigate to Java > Installed JREs and then click the "Add" button.
