### ISSUE TITLE
Ripples are clipped in ViewPagerTabActivity

### ISSUE THREAD

**Issue by vemacs** [ksoichiro/Android-ObservableScrollView#35]
![](http://i.imgur.com/EYBe4MG.png)

The Play Store, which presumably uses similar code with RecyclerViews, does not have this issue. I am experiencing this issue with my own app as well as the demo.

To reproduce, slide to the left or right on the first or last fragments.

**Comment by ksoichiro** [comment]
I fixed the issue and released to the Play store.
Thank you again for reporting this issue.
