### ISSUE TITLE
Problem with Fill Gap & ScrollVIew

### ISSUE THREAD

**Issue by panagorn** [ksoichiro/Android-ObservableScrollView#36]
Hello. I realised in this activity when i scroll fast down or app the sticky part with the title make some move and shows the layout that scrolling below, in gill gap with recycler view this is not happening.

And i have a question. Can i do ViewPagerTabActivity with fragment and no with activity? (I mean to extend fragment not activity and hide the supportActionbar thats the parent activity has)? I tried it and replace some staffs like setSupportActionBar because i had the actionbar from the activity but when i scroll up it doesnt hide. Thank you in advance

**Comment by ksoichiro** [comment]
I fixed the problem on FillGap and ScrollView and released to the Play store.

Please wait for the ViewPagerTab on Fragment pattern.

**Comment by ksoichiro** [comment]
@panagorn I have a question about your request.

> extend fragment not activity and hide the supportActionbar thats the parent activity has

Does it mean you're using nested fragments?
(Activity has ActionBar, and the activity has a fragment as a child, and this fragment has tabs, ViewPager and fragments as ViewPager's pages.)

**Comment by panagorn** [comment]
yes because i have a navigation drawer and i dont want to open other activities there is a fragment with tabs

**Comment by ksoichiro** [comment]
Thanks for your quick reply!
OK, I see. Please wait, I'm working on it.

**Comment by panagorn** [comment]
oki thank you

**Comment by ksoichiro** [comment]
I've added an example named `ViewPagerTabFragmentActivity`.
This activity has a toolbar, and a fragment `ViewPagerTabFragmentParentFragment` that manages tabs, ViewPager and each pages.
Please check if they satisfy your requirements.

**Comment by panagorn** [comment]
ok thank you i will check it later and i will tell you

**Comment by ksoichiro** [comment]
Closing.
Please reopen it if there are any problems related to this issue.

**Comment by gvsharma** [comment]
Hi....in some of the low resolution devices the tabs are displaying? and it is more specific for  480x800 resolution device?
