### ISSUE TITLE
Gradle Problem

### ISSUE THREAD

**Issue by acappelli** [ksoichiro/Android-ObservableScrollView#37]
Hi! 
I had try to add the new version on my project and gradle return this:
![screenshot 2015-01-02 10 56 25](https://cloud.githubusercontent.com/assets/1911447/5595252/2ed4490e-926e-11e4-9037-e4c13aa82ac7.png)

I change the version with 1.3.2 without errors..

**Comment by ksoichiro** [comment]
Hi!
It's strange. It has already been published to Maven Central.
http://search.maven.org/#artifactdetails|com.github.ksoichiro|android-observablescrollview|1.4.0|aar

Did you write this to your `build.gradle`?
```
repositories {
    mavenCentral()
}
```

**Comment by acappelli** [comment]
yes, can you try on a yours new project?

**Comment by ksoichiro** [comment]
I've tried on a new project, and there's no problem...

**Comment by acappelli** [comment]
Please can you send me your build.gradle?

**Comment by acappelli** [comment]
For clarify this is the my gradle's: https://gist.github.com/acappelli/7893d79be6fd6b92db7a

**Comment by acappelli** [comment]
I try from another computer and works fine! this is a mystery :-) I'm sorry for this!
