### ISSUE TITLE
clicks when scrolling down

### ISSUE THREAD

**Issue by erickChavez** [ksoichiro/Android-ObservableScrollView#38]
Hi, 
thank you for all your beautiful examples.

There is a bug that is annoying, in some listview examples when the user is on the topp of the list and is trying to scroll up(swiping down) then the item the user first touch is clicked or if the user scrolls up (swiping down) and holds then the onItemLongClick will be call for the fitrst touched item. So it is too easy to click on item when the user only swipes down at the top of the list.
The problem can be found at ToolbarControlListviewActivity

I hope I'm being clear about the problem :)

And another bug i found is when you scroll up and down fast then the toolbar/sticky toolbar  gets stuck and you are able to see and click at the padding views at the top of the list.

so both problems can be found at the same example, ToolbarControlListviewActivity with sticky view.

**Comment by ksoichiro** [comment]
Hi,
thank you for your feedback.

About the first one, do you mean that onClick event is fired on swiping?
I don't know what version of Android you're using,
but suppose you're using Lollipop, normal list item background has ripple effect on down event(ACTION_DOWN), and it does not mean onClick is fired.

And the second one, I understand. I'll check that later.

**Comment by erickChavez** [comment]
Well the bug is really easy to find in Samsung s4 version 4.4.2, it happens almost every time, but in the samsung s2 version 4.1.2 and note pro 12 the bug appears only sometimes. 

Well it is the OnItemClickedListener that is fired on swiping down at top of the listview or on holding at the end of the swipe the onItemLongClicked will be trigged.

**Comment by ksoichiro** [comment]
Thank you for your information.
I fixed the issues.
One of the issue was inside the library,
so if you want to try it in your own app, use "1.5.0-SNAPSHOT":

```groovy
repositories {
    mavenCentral()
    maven {
        url uri('https://oss.sonatype.org/content/repositories/snapshots/')
    }
}

dependencies {
    compile "com.github.ksoichiro:android-observablescrollview:1.5.0-SNAPSHOT"
}
```

**Comment by erickChavez** [comment]
The click problem is solved now, great job.
The padding now wokrs too but it blinks now at the top of the listview.

**Comment by ksoichiro** [comment]
Thanks for checking and sorry about the blinking. I'll fix it soon.

**Comment by ksoichiro** [comment]
Finally I fixed it.
It was a difficult problem and I slightly changed the behavior based on ViewPagerTab example.

**Comment by erickChavez** [comment]
Nice, thank you, it works now 👍
I appreciate your work, really nice

**Comment by comeondude** [comment]
I've an action bar and there's two tabs below it. I want the action bar to hide when the listview in each tab scrolls up and show the action bar while scrolling down. I've used your library and it worked like a charm except for one issue I'm facing now. It blinks in between the action bar and the tabs while scrolling up and down. Is this issue seems familiar to you?

**Comment by davemg3** [comment]
Similar issue with https://github.com/ksoichiro/Android-ObservableScrollView/issues/285
Do you have any clue on how to solve this?
I spent so many days to try to solve this...
