### ISSUE TITLE
getScreenHeight() method missing in ViewPagerTabFragmentParentFragment.java

### ISSUE THREAD

**Issue by timkatgert** [ksoichiro/Android-ObservableScrollView#39]
Hi, I really like your library, but I'm having some problems with implementing it.
I'm missing the getScreenHeight() method inside class ViewPagerTabFragmentParentFragment.java
I'm using Eclipse (and yes i know i have to import alot of other libraries, but I have already got an example of you working).

Hope you can help me

Thanks

**Comment by xu6148152** [comment]
you can import the project into android studio, then it will be ok.
