### ISSUE TITLE
Toolbar with Observable List View

### ISSUE THREAD

**Issue by AkshayChordiya** [ksoichiro/Android-ObservableScrollView#43]
Hi, 
Thank you for this library. I'm using it since many days, previously with Action Bar but now I have switched to Toolbar but when scrolling the ListView causes some weird scrolling feel. Like it's moving to adjust things. 
I checked your samples but it had either Action Bar with Observable Scroll View or Toolbar with Sticky. 

I hope you get what I am saying. In short I just mean to have a smooth hiding of toolbar when scrolling though the list. 

Thank you.

**Comment by ksoichiro** [comment]
Thank you for your feedback.
I'll try put some examples later.

**Comment by AkshayChordiya** [comment]
Yeah sure, Thank you. 
You can check inbox app, if possible effect like that.

**Comment by AkshayChordiya** [comment]
@ksoichiro 
Have you got what problem I am facing ?

**Comment by AkshayChordiya** [comment]
@ksoichiro 
Any progress ?
I tried translating the ```Toolbar``` but it left a white space

**Comment by ksoichiro** [comment]
@AkshayChordiya 
Sorry for being late.
I added new ToolbarControl examples.
Old ToolbarControl\*Activities are renamed to StickyHeader\*Activities.

**Comment by AkshayChordiya** [comment]
@ksoichiro 
It's better late than never.
Thank you so much. I'm checking them out, but meanwhile I created by own ```Toolbar``` animation.

**Comment by AkshayChordiya** [comment]
Here is what I did

```
switch (scrollState) {
            case UP:
                toolbar.animate().cancel();
                toolbar.animate().translationY(-toolbarHeight).setDuration(200).start();
                mFABShuffle.hide();
                break;
            case DOWN:
                toolbar.animate().cancel();
                toolbar.animate().translationY(0).setDuration(200).start();
                mFABShuffle.show();
                break;
        }
```
