### ISSUE TITLE
callback onScrollChanged big delay

### ISSUE THREAD

**Issue by dvasko** [ksoichiro/Android-ObservableScrollView#49]
Example of output:
01-16 10:53:26.967  scrollPosition: 181
01-16 10:53:26.981  scrollPosition: 156
01-16 10:53:26.998  scrollPosition: 128
01-16 10:53:27.015  scrollPosition: 101
01-16 10:53:27.032  scrollPosition: 75
01-16 10:53:27.048  scrollPosition: 46
01-16 10:53:27.065  scrollPosition: 17
01-16 10:53:27.216  scrollPosition: 0

All callback between position are < 20ms, but last on scrollY position 0 is delayed by more than 140ms which causes laggy effect on end of scroll. I checked your examples and same thing occurs on onScrollChanged callback where scrollY = 0.
FlexiableSpaceListView example

**Comment by ksoichiro** [comment]
Thank you for your feedback.

I checked the `FlexibleSpaceWithImageListViewActivity` on Android 5.0 and 4.3 but couldn't find your issue.
Could you tell me Android OS version that you're using?

**Comment by dvasko** [comment]
Nexus 5, 5.0.1
