### ISSUE TITLE
The floatbutton isn't triggered when clicked with API 8.

### ISSUE THREAD

**Issue by alburaawi** [ksoichiro/Android-ObservableScrollView#58]
I'm testing the library and everything works fine with my API-21 phone, the floatbutton is triggered when clicked. However, when I try it with API-8 most of the things works good except the floatbutton in **FlexibleSpaceWithImageListViewActivity** class it's not triggered, likewise when I used a different floatbutton to **melnykov's** one the same happens and nothing is triggered.

I set the view to clickable in xml, and typed the following code and no luck:
```java
mFab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                // TODO Auto-generated method stub
                Log.v("mFab1:" , "Do you want change color of this button to red?");
            }
        });
```

I also tried setting the floatbutton as a button and no luck.

Any suggestions? 
Thank you very much.

**Comment by ksoichiro** [comment]
Thank you for your report.
I couldn't test it on API level 8, but I confirmed this issue also happens on API level 10, and I fixed it with these changes:

* Set margins to FAB instead of using `ViewHelper.setTranslationX/Y`.
* Set `android:layout_gravity="left|top"` to FAB explicitly. Without this, setting margins to LayoutParams doesn't work.
* Replace `ViewHelper.getTranslationY` because translationY is not changed.

Please check the commit ef6e1db.

**Comment by alburaawi** [comment]
That's amazing, thank you very much.
I tried it and it works perfect.

I noticed an issue in the same class regarding the toolbar title when set to a different language (Right-to-Left languages e.g. Arabic), it goes to the right-handside off the screen and you can only see the last word if not the full title.

I didn't have a chance to look at the whole project, but it could be a minor issue. Any ideas what could be the cause or what to change?

**Comment by ksoichiro** [comment]
Thanks for checking.

Sorry, I don't understand the second issue.
Could you show me a screenshot?

**Comment by alburaawi** [comment]
No worries mate.
Look at the title on the top of the floating action button, it only shows the last word:

![screenshot_2015-02-02-19-02-14](https://cloud.githubusercontent.com/assets/5963646/6003743/f6b2f624-ab0e-11e4-8d51-206599b8bc42.png)



And when I scroll up, the full title is shown:

![screenshot_2015-02-02-19-02-21](https://cloud.githubusercontent.com/assets/5963646/6003746/0154689c-ab0f-11e4-96cc-6a212fd0b206.png)

This happens when I use the Arabic language (right-to-left language).

**Comment by ksoichiro** [comment]
Thanks!
I fixed it in the commit e60a0cd.
The main problem was `ViewHelper.setPivotX(mTitleView, 0)`.
You shouldn't set 0 if you support RTL.

**Comment by alburaawi** [comment]
I just tested it and for some reason I'm experiencing the same issue mentioned above!! Very starnge. 
I tested it with my nexus 5.

**Comment by ksoichiro** [comment]
That's strange.
Does it happen on your app or my example?

**Comment by alburaawi** [comment]
It happens on my app, however, I copied and pasted the same class and xml file from **e60a0cd** commit. 
I'm not sure if I need to specify somewhere in the app to support RTL!

**Comment by alburaawi** [comment]
This did the trick, I've tested it in different versions and it seems to be working with no problems.
```java
private void setPivotXToTitle() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
            ViewHelper.setPivotX(mTitleView, findViewById(android.R.id.content).getWidth());
        } else {
            ViewHelper.setPivotX(mTitleView, 0);
        }
}
```

Thanks mate.
