### ISSUE TITLE
FlexibleSpaceWithImageScrollView Header image still showing after scroll

### ISSUE THREAD

**Issue by LeCompanero** [ksoichiro/Android-ObservableScrollView#61]
I'm trying to make an app based upon your sample, but I'm getting this artifact when I scroll down the screen and have little text below the toolbar.

![screenshot_2015-02-02-10-08-30](https://cloud.githubusercontent.com/assets/10760738/6000439/04a18efc-aac5-11e4-8e57-2c86d81e81ec.png)
![screenshot_2015-02-02-10-08-39](https://cloud.githubusercontent.com/assets/10760738/6000440/062d0f30-aac5-11e4-9f48-46514333bdb7.png)

**Comment by ksoichiro** [comment]
Maybe your ScrollView's content has transparent background.
Please try setting `android:background` to your child view of the ScrollView.

**Comment by LeCompanero** [comment]
This solved the problem, but I had to separate the Linear Layouts, one for my text "Teste" in first image, and the CardView on the second LinearLayout (this I setup android:background). Thanks for helping
