### ISSUE TITLE
Help setting up ObservableScrollView

### ISSUE THREAD

**Issue by dirkam** [ksoichiro/Android-ObservableScrollView#86]
Can you please help me how can I use this library to hide/show the toolbar just like Google Play app does?

I have a main activity and several fragments.
Activity layout:
```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">


    <android.support.v4.widget.DrawerLayout
        android:id="@+id/drawer_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <!-- The main content view -->
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <include layout="@layout/toolbar" />

            <com.astuetz.PagerSlidingTabStrip
                android:id="@+id/tabs"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:background="?attr/colorPrimary"
                app:pstsIndicatorColor="@color/primary_text_default_material_dark"
                app:pstsTextColorSelected="@color/primary_text_default_material_dark"
                app:pstsPaddingMiddle="true"/>

            <android.support.v4.view.ViewPager
                android:id="@+id/pager"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />
        </LinearLayout>

        <!-- The navigation drawer -->
        <include layout="@layout/navdrawer" />

    </android.support.v4.widget.DrawerLayout>
</LinearLayout>
```
Fragment:
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.github.ksoichiro.android.observablescrollview.ObservableRecyclerView
        android:id="@+id/rcyclrVwWatchlist"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clipToPadding="false"
        android:paddingLeft="@dimen/watchlist_list_padding"
        android:paddingTop="@dimen/watchlist_list_padding"
        android:scrollbarStyle="outsideOverlay"
        android:scrollbars="vertical" />
</RelativeLayout>
```
How can I achieve this? What sample should I check for this?

Thanks

**Comment by franciscerio** [comment]
up

**Comment by f4cker** [comment]
You could implements the `ObservableScrollViewCallbacks` in your fragments,and then find your views you want to interact with in `onAttach()` method in your fragment,at last,complete the `onScrollChanged()`,`onDownMotionEvent()`, `onUpOrCancelMotionEvent` method and enjoy it!

**Comment by dirkam** [comment]
Thanks @f4cker, do you happen to have a working example?

**Comment by f4cker** [comment]
[Look here][1],the source @dirkam 
[1]:https://github.com/f4cker/obeservable_fragment.git

**Comment by dirkam** [comment]
@f4cker thank you very much, based on this I could set it up. Do you happen to know how can I sync the toolbar state among fragments? In your example if toolbar is hidden on fragment A and you switch fragment B then there will be a gap between the tabs and the recyclerview.

**Comment by f4cker** [comment]
you could try to create a boolean to record the `toolbar`'s state and user `bundle args` transfer from `fragment a` to `fragment b` and then judge the boolean to set the `toolbar`'s state @dirkam

**Comment by dirkam** [comment]
Well, it took me several hours to figure it out but with your help I was able to implement what I need. Thanks @f4cker

**Comment by vibinr** [comment]
How do you make the ListView increase its width as Toolbar translates in Y direction? I see empty space in mine https://github.com/ksoichiro/Android-ObservableScrollView/issues/102

**Comment by vibinr** [comment]
I even tried setting negative marginTop to headerview (toolbar+tabs), but it stutters while I scroll the listview.

**Comment by f4cker** [comment]
@vibinr could you show me your code and screenshot?

**Comment by vibinr** [comment]
@f4cker I have actually created this as a new issue: https://github.com/ksoichiro/Android-ObservableScrollView/issues/102, can you please answer it there? I have posted the XML code and links to screenshots. 

Thanks a lot!
