### ISSUE TITLE
FlexibleSpaceWithImageWithViewPagerTab2Activity is lagging when used with custom fragment listview adapter

### ISSUE THREAD

**Issue by IvoHerka** [ksoichiro/Android-ObservableScrollView#87]
From what I discovered, the problem is caused by calling  mInterceptionLayout.requestLayout(); in onMoveMotionEvent()

**Comment by lukas1994** [comment]
+1

**Comment by claudiopizzillo** [comment]
+1

**Comment by thiagomanel** [comment]
+1

**Comment by BackPackerDz** [comment]
+1

**Comment by audiebantzhan** [comment]
+1

**Comment by Jalcubo** [comment]
I solved this problem.

First, on onMoveMotionEvent() I deleted this lines:

/*if (translationY < 0) {
                FrameLayout.LayoutParams lp = (FrameLayout.LayoutParams) mInterceptionLayout.getLayoutParams();
                lp.height = (int) (-translationY + getScreenHeight());
                mInterceptionLayout.requestLayout();
            }*/

And copy below of mInterceptionLayout's assignement , on Oncreate for example:

FrameLayout.LayoutParams lp = (FrameLayout.LayoutParams) mInterceptionLayout.getLayoutParams();
            lp.height = getScreenHeight() + mFlexibleSpaceHeight;
            mInterceptionLayout.requestLayout();

This avoids loading the adapter with each move.

**Comment by lukas1994** [comment]
This can't work. It is necessary to change the height in ```onMoveMotionEvent()```.

**Comment by Jalcubo** [comment]
Works for me, because I defne a extra height ( getScreenHeight() + mFlexibleSpaceHeight) to create a listview with the size of the screen, and it isn't necessary change the element that the listview must to show

**Comment by lukas1994** [comment]
Cool thanks, I figured it out.

**Comment by ksoichiro** [comment]
@Jalcubo Excellent solution, thanks! I applied the code to the sample.

**Comment by Jalcubo** [comment]
@ksoichiro  I'm glad to help you, and thanks for your code
