### ISSUE TITLE
Making tool bar not scroll up <Solved>

### ISSUE THREAD

**Issue by chihao12** [ksoichiro/Android-ObservableScrollView#89]
hi there, i am using your sample , FlexibleSpaceWithImageScrollViewActivity, i saw your first gif where the toolbar becomes solid and doesnt scroll up along with the text below. But your current sample scrolls the toolbar up along with the text below. 

Can i ask how do i achieve the toolbar becoming solid and not scroll up? 

Thanks

**Comment by borgwald** [comment]
Would have been nice, if you've posted your solution.
